services:
  rpc_cpu:
    image: llama.cpp/cpu:latest
    restart: "unless-stopped"
    #build:
    #  context: ./llama.cpp
    #  dockerfile: Dockerfile.cuda
    #  args:
    #    - LLAMACPP_VERSION=b3700
    environment:
      # Operation mode (RPC servyyer)
      APP_MODE: backend
      APP_MEM: 4096 # MBytes RAM
    ports:
      - "192.168.0.143:50252:50052"

  rpc_cuda0:
    image: llama.cpp/cuda:latest
    restart: "unless-stopped"
    environment:
      APP_MODE: backend
      APP_MEM: 8000 # MBytes VRAM
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"] 
              capabilities: [ gpu ]
    ports:
      - "192.168.0.143:50253:50052"

  rpc_cuda1:
    image: llama.cpp/cuda:latest
    restart: "unless-stopped"
    environment:
      APP_MODE: backend
      APP_MEM: 8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"] 
              capabilities: [ gpu ]
    ports:
     - "192.168.0.143:50254:50052"

